### ISSUE TITLE
Facing issue javax.jms.JMSException: Could not connect to broker URL: tcp://localhost:61616. Reason: java.net.ConnectException: Connection refused[BUG]

### ISSUE THREAD

**Issue by Pratham9850** [streamnative/pulsar-io-activemq#20]
**Description:**
I am facing an issue while trying to connect ActiveMQ to Apache Pulsar using the pulsar-io-activemq-0.0.1 NAR file. Here are the details of the issue:

**Additional Information:**

Pulsar Version: 3.1.0
ActiveMQ Version: 3 latest (Both pulsar and activemq are running on docker)
Connector Version: 2.5.1 and 0.0.1 both tried

**Configuration File:**
tenant: "public"
namespace: "default"
name: "activemq-source"
topicName: "demoPulsarTopic"
archive: "connectors/pulsar-io-activemq-0.0.1.nar"
parallelism: 1

configs:
    protocol: "tcp"
    host: "localhost"
    port: "61616"
    username: "admin"
    password: "admin"
    queueName: "demoQueue"

Command used: bin/pulsar-admin source localrun --source-config-file ./connectors/activemq-source.yaml

**Error Encountered:**
 ERROR org.apache.pulsar.functions.runtime.RuntimeSpawner - public/default/activemq Function Container is dead with following exception. Restarting.
javax.jms.JMSException: Could not connect to broker URL: tcp://localhost:61616. Reason: java.net.ConnectException: Connection refused
        at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:36) ~[?:?]
        at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:374) ~[?:?]
        at org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:252) ~[?:?]
        at org.apache.pulsar.ecosystem.io.activemq.ActiveMQSource.open(ActiveMQSource.java:67) ~[?:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setupInput(JavaInstanceRunnable.java:868) ~[org.apache.pulsar-pulsar-functions-instance-3.1.0.jar:3.1.0]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setup(JavaInstanceRunnable.java:263) ~[org.apache.pulsar-pulsar-functions-instance-3.1.0.jar:3.1.0]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:300) ~[org.apache.pulsar-pulsar-functions-instance-3.1.0.jar:3.1.0]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
        at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
        at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.net.Socket.connect(Socket.java:633) ~[?:?]
        at org.apache.activemq.transport.tcp.TcpTransport.connect(TcpTransport.java:525) ~[?:?]
        at org.apache.activemq.transport.tcp.TcpTransport.doStart(TcpTransport.java:488) ~[?:?]
        at org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55) ~[?:?]
        at org.apache.activemq.transport.AbstractInactivityMonitor.start(AbstractInactivityMonitor.java:169) ~[?:?]
        at org.apache.activemq.transport.InactivityMonitor.start(InactivityMonitor.java:52) ~[?:?]
        at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64) ~[?:?]
        at org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:72) ~[?:?]
        at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64) ~[?:?]
        at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64) ~[?:?]
        at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:354) ~[?:?]
**Attempted Solution:**
I tried modifying the configurations as follows:
Command used:  ./bin/pulsar-admin source localrun \
  --archive ./connectors/pulsar-io-activemq-0.0.1.nar \
  --tenant public \
  --namespace default \
  --name activemq \
  --destination-topic-name activemq-topic \
  --source-config-file ./connectors/activemq-source.yaml \
  --parallelism 1

pulsarIO:
  adminUrl: "http://localhost:8080"
  webServiceUrl: "http://localhost:8080"
  pulsarServiceUrl: "pulsar://localhost:6650"
  topic: "persistent://public/default/demoPulsarTopic"
  subscriptionName: "activemq-subscription"
  activeMQ:
    brokerURL: "tcp://localhost:61616"
    configs:
      host: "localhost"
      port: "61616"
      username: "admin"
      password: "admin"
      queueName: "demoQueue"
      protocol: "tcp"

**Error Encountered After Modification:** 
 ERROR org.apache.pulsar.functions.runtime.RuntimeSpawner - public/default/activemq Function Container is dead with following exception. Restarting.
java.lang.NullPointerException: protocol property not set.
        at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]
        at org.apache.pulsar.ecosystem.io.activemq.ActiveMQConnectorConfig.validate(ActiveMQConnectorConfig.java:60) ~[?:?]
        at org.apache.pulsar.ecosystem.io.activemq.ActiveMQSource.open(ActiveMQSource.java:61) ~[?:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setupInput(JavaInstanceRunnable.java:868) ~[org.apache.pulsar-pulsar-functions-instance-3.1.0.jar:3.1.0]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setup(JavaInstanceRunnable.java:263) ~[org.apache.pulsar-pulsar-functions-instance-3.1.0.jar:3.1.0]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:300) ~[org.apache.pulsar-pulsar-functions-instance-3.1.0.jar:3.1.0]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

Request for Assistance:
I am seeking assistance to resolve this issue. Any insights or alternative approaches to configure the pulsar-io-activemq connector properly would be greatly appreciated.

**Comment by Pratham9850** [comment]
If you are using docker make sure to create a network bridge between activemq and apache pulsar container to resolve the issue. And also make sure to change the hostname from "localhost" to "172......." that's present in the network bridge. Link for the network bridge: https://docs.docker.com/network/network-tutorial-standalone/
